// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxvebkgxnewfiacywheu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dmVia2d4bmV3ZmlhY3l3aGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjM2NDUsImV4cCI6MjA2OTgzOTY0NX0.q0cI2idGqiYFSWlX90ZxW22vIJ1C_AMrRQq9gAiReZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});